[package]
name = "steam-auto"
version = "1.0.2"
description = "Steam Fake Library & Unlocker Tool"
authors = ["SteamAuto Team"]
edition = "2021"

[lib]
name = "steam_auto_lib"
crate-type = ["staticlib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.2.0", features = ["tray-icon"] }
tauri-plugin-opener = "2.2.0"
tauri-plugin-dialog = "2.2.0"
tauri-plugin-fs = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zip = { version = "2.2.0", default-features = false, features = ["deflate"] }
winreg = "0.52"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1.40", features = ["full"] }
sysinfo = "0.32"
regex = "1.10"
chrono = "0.4"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
