use std::fs;
use std::path::Path;

// Embed the complete OpenSteamTool DLL suite
pub const EMBEDDED_OST_DLL: &[u8] = include_bytes!("../../resources/OpenSteamTool.dll");
pub const EMBEDDED_DWMAPI_DLL: &[u8] = include_bytes!("../../resources/dwmapi.dll");
pub const EMBEDDED_XINPUT_DLL: &[u8] = include_bytes!("../../resources/xinput1_4.dll");

pub const DEFAULT_OST_CONFIG: &str = r#"# opensteamtool.toml generated by SteamAuto
[log]
level = "info"

[manifest]
# 上游清单请求码接口: "opensteamtool", "wudrm", "steamrun"
url = "opensteamtool"
timeout_resolve_ms = 5000
timeout_connect_ms = 5000
timeout_send_ms    = 10000
timeout_recv_ms    = 10000

[stats]
enable_api = true

[lua]
# 同时监听并加载 config/lua 与 config/stplug-in 目录下的所有 Lua 配置
paths = ["config/stplug-in", "config/lua"]

[inject]
enabled = false
"#;

const DLL_FILES: [&str; 3] = ["OpenSteamTool.dll", "dwmapi.dll", "xinput1_4.dll"];

pub fn is_unlock_enabled(steam_path: &Path) -> bool {
    steam_path.join("OpenSteamTool.dll").exists() || steam_path.join("xinput1_4.dll").exists()
}

fn ensure_unlock_environment(steam_path: &Path) {
    let _ = fs::create_dir_all(steam_path.join("config").join("lua"));
    let _ = fs::create_dir_all(steam_path.join("config").join("stplug-in"));
    let _ = fs::create_dir_all(steam_path.join("depotcache"));

    let toml_path = steam_path.join("opensteamtool.toml");
    if !toml_path.exists() {
        let _ = fs::write(&toml_path, DEFAULT_OST_CONFIG);
    }
}

pub fn enable_unlock_mode(steam_path: &Path) -> Result<String, String> {
    let dll_payloads: [(&str, &[u8]); 3] = [
        ("OpenSteamTool.dll", EMBEDDED_OST_DLL),
        ("dwmapi.dll", EMBEDDED_DWMAPI_DLL),
        ("xinput1_4.dll", EMBEDDED_XINPUT_DLL),
    ];

    for (name, payload) in dll_payloads {
        let target = steam_path.join(name);
        let disabled = steam_path.join(format!("{}.disabled", name));

        if disabled.exists() && !target.exists() {
            let _ = fs::rename(&disabled, &target);
        } else if !target.exists() {
            let _ = fs::write(&target, payload);
        }
    }

    ensure_unlock_environment(steam_path);

    Ok("解锁模式已开启！已完整部署 OpenSteamTool.dll、dwmapi.dll、xinput1_4.dll 及配置文件，重启 Steam 即可生效".to_string())
}

pub fn disable_unlock_mode(steam_path: &Path) -> Result<String, String> {
    for name in DLL_FILES {
        let target = steam_path.join(name);
        let disabled = steam_path.join(format!("{}.disabled", name));

        if target.exists() {
            if disabled.exists() {
                let _ = fs::remove_file(&disabled);
            }
            let _ = fs::rename(&target, &disabled);
        }
    }

    Ok("解锁模式已关闭（所有解锁 DLL 已停用，恢复为官方原生模式）".to_string())
}

pub fn repair_unlock_dll(steam_path: &Path) -> Result<String, String> {
    let dll_payloads: [(&str, &[u8]); 3] = [
        ("OpenSteamTool.dll", EMBEDDED_OST_DLL),
        ("dwmapi.dll", EMBEDDED_DWMAPI_DLL),
        ("xinput1_4.dll", EMBEDDED_XINPUT_DLL),
    ];

    for (name, payload) in dll_payloads {
        let target = steam_path.join(name);
        let disabled = steam_path.join(format!("{}.disabled", name));

        if disabled.exists() {
            let _ = fs::remove_file(&disabled);
        }

        let _ = fs::write(&target, payload);
    }

    let toml_path = steam_path.join("opensteamtool.toml");
    let _ = fs::write(&toml_path, DEFAULT_OST_CONFIG);

    ensure_unlock_environment(steam_path);

    Ok("OpenSteamTool 完整 DLL 套件（OpenSteamTool.dll、dwmapi.dll、xinput1_4.dll）与配置文件已重置并修复成功".to_string())
}
